packages:
  - wanted:
    - screen
    - vim
  - unwanted:
    - grub2-snapper-plugin
    - snapper
    - snapper-zypp-plugin
    - yast2-snapper
    - libsnapper3
    - plymouth-scripts
    - plymouth-plugin-script
    - plymouth-plugin-label-ft
    - libtracker-miner-1_0-0
